### ISSUE TITLE
Error in Orleans.TestingHost.TestCluster

### ISSUE THREAD

**Issue by sithwin** [petabridge/NBench#145]
Hi,

I am using xUnit and Orleans.TestingHost.TestCluster to test my grain methods but I'm having following exception. Is it possible to do performance test with NBench and TestCluster?

Thanks!

`NBench.NBenchException: Error occurred during $Vendors.Tests.VendorsTest+CreateVendorWithSameIdFails SETUP. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.Serialization.SerializationException: Type is not resolved for member 'Orleans.Runtime.Silo+SiloType,OrleansRuntime, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null'.
   at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at Orleans.TestingHost.TestCluster.LoadSiloInNewAppDomain(String siloName, SiloType type, ClusterConfiguration config, AppDomain& appDomain)
   at Orleans.TestingHost.TestCluster.StartOrleansSilo(TestCluster cluster, SiloType type, ClusterConfiguration clusterConfig, NodeConfiguration nodeConfig)
   at Orleans.TestingHost.TestCluster.<InitializeAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.TestingHost.TestCluster.<DeployAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Orleans.TestingHost.TestCluster.Deploy(IEnumerable`1 siloNames)
   at Infrastructure.Orleans.Testing.ApeTestCluster..ctor(Action`1 configureOptions) in C:\Workspace\Ape.Backend\Infrastructure.Orleans.Testing\ApeTestCluster.cs:line 21
   at Vendors.Tests.VendorsTest..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at NBench.Sdk.ReflectionBenchmarkInvoker.InvokePerfSetup(BenchmarkContext context)
   at NBench.Sdk.Benchmark.PreRun()
   --- End of inner exception stack trace ---
NBench.NBenchException: Error occurred during $Vendors.Tests.VendorsTest+CreateVendorWithSameIdFails RUN. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NBench.Sdk.ReflectionBenchmarkInvoker.InvokeRun(BenchmarkContext context)
   at NBench.Sdk.Benchmark.WarmUp()
   --- End of inner exception stack trace ---
NBench.NBenchException: Error occurred during $Vendors.Tests.VendorsTest+CreateVendorWithSameIdFails CLEANUP. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NBench.Sdk.ReflectionBenchmarkInvoker.InvokePerfCleanup(BenchmarkContext context)
   at NBench.Sdk.Benchmark.PostRun()
   --- End of inner exception stack trace ---`

**Comment by Aaronontheweb** [comment]
hi there @sithwin

Could you post a brief code sample of the spec you were trying to run?

**Comment by sithwin** [comment]
Hi @Aaronontheweb ,

Sorry for the lack of information. The solution name is HellowWorld.SingleProcess and SiloTests is the test project. You could download the whole solution  [here](https://github.com/dotnet/orleans/tree/master/Samples/HelloWorld).

I installed NBench in the test project and tried to run the runner.

Here is my code:
`public class HelloWorldSiloTests : IClassFixture<OrleansSiloFixture>
    {
        private readonly OrleansSiloFixture _fixture;

        public HelloWorldSiloTests(OrleansSiloFixture fixture)
        {
            _fixture = fixture;
        }

        private IGrainFactory GrainFactory => _fixture.Cluster.GrainFactory;


        private Counter _counter;

        [PerfSetup]
        public void Setup(BenchmarkContext context)
        {
            _counter = context.GetCounter("TestCounter");
        }

        [PerfBenchmark(Description = "Test to ensure that a minimal throughput test can be rapidly executed.",
            NumberOfIterations = 3, RunMode = RunMode.Throughput,
            RunTimeMilliseconds = 1000, TestMode = TestMode.Test)]
        [CounterThroughputAssertion("TestCounter", MustBe.GreaterThan, 10000000.0d)]
        [MemoryAssertion(MemoryMetric.TotalBytesAllocated, MustBe.LessThanOrEqualTo, ByteConstants.ThirtyTwoKb)]
        [GcTotalAssertion(GcMetric.TotalCollections, GcGeneration.Gen2, MustBe.ExactlyEqualTo, 0.0d)]
        public void Benchmark()
        {
            _counter.Increment();
        }

        [PerfCleanup]
        public void Cleanup()
        {
            // does nothing
        }

        [Fact]
        public async Task SiloSayHelloTest()
        {
            // The Orleans silo / client test environment is already set up at this point.

            long id = new Random().Next();
            const string greeting = "Bonjour";

            IHello grain = GrainFactory.GetGrain<IHello>(id);

            // This will create and call a Hello grain with specified 'id' in one of the test silos.
            string reply = await grain.SayHello(greeting);

            Assert.NotNull(reply);
            Assert.Equal($"You said: '{greeting}', I say: Hello!", reply);
        }

        [Fact]
        public async Task SiloSayHelloArchiveTest()
        {
            long id = new Random().Next();
            const string greeting1 = "Bonjour";
            const string greeting2 = "Hei";

            IHelloArchive grain = GrainFactory.GetGrain<IHelloArchive>(id);

            // This will directly call the grain under test.
            await grain.SayHello(greeting1);
            await grain.SayHello(greeting2);

            var greetings = (await grain.GetGreetings()).ToList();

            Assert.Contains(greeting1, greetings);
            Assert.Contains(greeting2, greetings);
        }
    }

    /// <summary>
    /// Class fixture used to share the silos between multiple tests within a specific test class.
    /// </summary>
    public class OrleansSiloFixture : IDisposable
    {
        public TestCluster Cluster { get; }

        public OrleansSiloFixture()
        {
            GrainClient.Uninitialize();

            var options = new TestClusterOptions(initialSilosCount: 2);
            options.ClusterConfiguration.AddMemoryStorageProvider("Default");
            options.ClusterConfiguration.AddMemoryStorageProvider("MemoryStore");
            Cluster = new TestCluster(options);

            if (Cluster.Primary == null)
            {
                Cluster.Deploy();
            }
        }

        /// <summary>
        /// Clean up the test fixture once all the tests have been run
        /// </summary>
        public void Dispose()
        {
            Cluster.StopAllSilos();
        }
    }`

Please let me know what wrong with my code.

Thanks a lot!

**Comment by Horusiath** [comment]
AFAIK, NBench test runner requires perf test class to have a single parameterless constructor.
